# configs/agent_config.yaml

agent:
  # Which agent class to use: dqn, ppo, random
  type: dqn

  # All hyperparameters that your agent’s constructor
  # and update() routine will consume
  hyperparams:
    # Common DQN params
    lr: 0.0001                 # learning rate
    gamma: 0.99                # discount factor
    batch_size: 64             # minibatch size
    replay_buffer_size: 100000 # max transitions to store
    target_update_freq: 1000   # how often (in steps) to sync target net

    # Exploration schedule
    epsilon_start: 1.0
    epsilon_end: 0.01
    epsilon_decay_steps: 50000
